using Microsoft.AspNetCore.Components;
using Microsoft.EntityFrameworkCore;
using Test.Models;
using OpenAI.Chat;
namespace test.Components.Pages;

public partial class QuizEngine
{
    [Parameter]
    public int QuizId { get; set; }

    private Quiz? quiz;
    private List<Question> questions = new();
    private Dictionary<Question, List<Answer>> questionAnswers = new();
    private Dictionary<int, int> selectedAnswers = new();
    private bool loading = true;
    private bool quizSubmitted = false;
    private float score = 0;
    private float totalPossibleScore = 0;
    private int? currentStudentId;

    // Property to store feedback generated by GPT
    private string? feedback;

    // New properties for timed questions
    private int currentQuestionIndex = 0;
    private int timeLeft = 0;
    private System.Threading.Timer? timer;

    // Add this property to check if user is an educator
    private bool isEducator => !currentStudentId.HasValue;

    protected override async Task OnInitializedAsync()
    {
        await GetCurrentStudentId();

        // Only check max attempts for students, not educators
        if (!isEducator && await HasReachedMaxAttempts())
        {
            // Redirect to quiz list with an error message
            Navigation.NavigateTo("/quiz-list?error=maxattempts");
            return;
        }

        await LoadQuiz();
    }

    protected override void OnAfterRender(bool firstRender)
    {
        if (firstRender && questions.Count > 0 && !quizSubmitted)
        {
            StartTimerForCurrentQuestion();
        }
    }

    public void Dispose()
    {
        timer?.Dispose();
    }

    private async Task GetCurrentStudentId()
    {
        try
        {
            // Get the current user
            var user = await UserManager.GetUserAsync(HttpContextAccessor.HttpContext!.User);

            if (user != null)
            {
                // Find the corresponding Student entity using the username
                var student = await DbContext.Students.FirstOrDefaultAsync(s => s.Username == user.UserName);

                if (student != null)
                {
                    currentStudentId = student.StudentId;
                    Logger.LogInformation("Current student ID: {StudentId}", currentStudentId);
                }
                else
                {
                    // Handle case where there's no matching student in the custom table
                    Logger.LogError("No matching student found in Students table");
                }
            }
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "Error getting current student ID: {Message}", ex.Message);
        }
    }

    private async Task LoadQuiz()
    {
        try
        {
            // Fetch the quiz with its questions and answers
            quiz = await DbContext.Quizzes.FindAsync(QuizId);
            if (quiz == null)
            {
                loading = false;
                return;
            }

            // Load questions for this quiz
            questions = await DbContext.Questions
                .Where(q => q.QuizID == QuizId)
                .ToListAsync();

            // Randomize question order for students
            // Don't randomize for educators to maintain consistency in preview mode
            if (!isEducator)
            {
                RandomizeQuestions();
            }

            // Load answers for each question
            foreach (var question in questions)
            {
                var answers = await DbContext.Answers
                    .Where(a => a.QuestionID == question.QuestionID)
                    .ToListAsync();

                questionAnswers[question] = answers;
                totalPossibleScore += question.Score ?? 1;
            }

            // Initialize timer for the first question
            if (questions.Count > 0)
            {
                timeLeft = GetQuestionTimeLimit(questions[0]);
            }
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "Error loading quiz: {Message}", ex.Message);
            Console.WriteLine($"Error loading quiz: {ex.Message}");
        }
        finally
        {
            loading = false;
        }
    }

    private void SelectAnswer(int questionId, int answerId)
    {
        selectedAnswers[questionId] = answerId;
    }

    private int GetQuestionTimeLimit(Question question)
    {
        return question.QuestionDifficulty switch
        {
            Question.Difficulty.easy => 20,
            Question.Difficulty.medium => 40,
            Question.Difficulty.hard => 60,
            _ => 40  // Default fallback
        };
    }

    private void StartTimerForCurrentQuestion()
    {
        // Dispose of any existing timer
        timer?.Dispose();

        if (currentQuestionIndex < questions.Count)
        {
            var question = questions[currentQuestionIndex];
            timeLeft = GetQuestionTimeLimit(question);

            // Create new timer that ticks every second
            timer = new System.Threading.Timer(_ =>
            {
                timeLeft--;

                // When time runs out, move to next question
                if (timeLeft <= 0)
                {
                    InvokeAsync(() =>
                    {
                        NextQuestion();
                        StateHasChanged();
                    });
                }
                else
                {
                    InvokeAsync(StateHasChanged);
                }
            },
            null,
            0,
            1000); // Update every second
        }
    }

    private void NextQuestion()
    {
        // Stop the current timer
        timer?.Dispose();

        // Move to the next question if available
        if (currentQuestionIndex < questions.Count - 1)
        {
            currentQuestionIndex++;
            StartTimerForCurrentQuestion();
        }
        else
        {
            // We've reached the end of the questions
            currentQuestionIndex = questions.Count; // Move to the submit screen

            // Auto-submit the quiz after the last question times out
            InvokeAsync(async () =>
            {
                await SubmitQuiz();
                StateHasChanged();
            });
        }
    }

    private async Task<int> GetAttemptCount()
    {
        if (!currentStudentId.HasValue) return 0;

        try
        {
            // Get number of attempts for this quiz by this student
            int attemptCount = await DbContext.QuizAttempts
                .Where(a => a.QuizID == QuizId && a.StudentID == currentStudentId.Value)
                .CountAsync();
            
            return attemptCount;
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "Error checking quiz attempts: {Message}", ex.Message);
            return 0; // On error, assume no attempts
        }
    }

    private async Task<bool> HasReachedMaxAttempts()
    {
        int attemptCount = await GetAttemptCount();
        
        // Check if max attempts (2) has been ALREADY reached
        return attemptCount > 1;  // Changed from >= 2 to > 1
    }

    private async Task SubmitQuiz()
    {
        // Dispose of any active timer
        timer?.Dispose();

        // Calculate score
        foreach (var question in questions)
        {
            if (selectedAnswers.TryGetValue(question.QuestionID, out int answerId))
            {
                var answer = questionAnswers[question].FirstOrDefault(a => a.AnswerID == answerId);
                if (answer != null && answer.IsCorrect)
                {
                    score += question.Score ?? 1;
                }
            }
        }

        // Skip database operations for educators
        if (isEducator)
        {
            Logger.LogInformation("Educator preview completed - no attempt recorded");
            quizSubmitted = true;
            return;
        }

        // Create quiz attempt record in database for students
        try
        {
            if (currentStudentId == null)
            {
                // This shouldn't happen as we already checked isEducator
                Logger.LogError("Cannot save quiz attempt: No student ID found");
                return;
            }

            var attempt = new QuizAttempt
            {
                QuizID = QuizId,
                StudentID = currentStudentId.Value,
                TotalScore = score,
                IsCompleted = true
            };

            DbContext.QuizAttempts.Add(attempt);
            await DbContext.SaveChangesAsync();
            
            // Get the auto-generated attempt ID
            int attemptId = attempt.AttemptID;
            Logger.LogInformation("Quiz attempt saved for student ID: {StudentId}, Attempt ID: {AttemptId}", currentStudentId, attemptId);

            // Get attempt count (including the one we just added)
            int attemptCount = await GetAttemptCount();

            if (attemptCount == 1)
            {
                // Generate and save feedback using GPT-4o-mini
                await GenerateFeedback(attemptId);
            }
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "Error saving quiz attempt: {Message}", ex.Message);
        }

        quizSubmitted = true;
    }

    private async Task GenerateFeedback(int attemptId)
    {
        try
        {
            // Prepare the input for GPT
            var input = new
            {
                quizName = quiz?.QuizName,
                questions = questions.Select(q => new
                {
                    q.QuestionBody,
                    selectedAnswer = selectedAnswers.TryGetValue(q.QuestionID, out int answerId)
                        ? questionAnswers[q].FirstOrDefault(a => a.AnswerID == answerId)?.Body
                        : "No answer",
                    correctAnswer = questionAnswers[q].FirstOrDefault(a => a.IsCorrect)?.Body
                }),
                score,
                totalPossibleScore
            };

            // Initialize the ChatClient
            var apikey = Environment.GetEnvironmentVariable("OPENAI_API_KEY");

            if (string.IsNullOrEmpty(apikey))
            {
                Logger.LogError("OpenAI API key is not set in environment variables.");
                this.feedback = "Error: OpenAI API key is not set.";
                return;
            }

            var client = new ChatClient(model: "gpt-4o-mini", apiKey: apikey);

            // Create the prompt
            string prompt = @"Provide feedback (a concise paragraph) for the following quiz attempt. Analyze the student's performance and provide
                            constructive feedback. Focus on areas where they could improve based on incorrect answers. Don't
                            expect any requests and don't sendback the questions and answers. Quiz data: "
                + System.Text.Json.JsonSerializer.Serialize(input);

            // Generate feedback
            ChatCompletion completion = await client.CompleteChatAsync(prompt);

            if (completion.Content.Any())
            {
                var feedbackText = completion.Content[0].Text;
                Logger.LogInformation("Feedback generated: {Feedback}", feedbackText);

                // Store feedback in a property to display in the UI
                this.feedback = feedbackText;
                
                // Save the feedback to database
                var quizFeedback = new QuizFeedback
                {
                    AttemptID = attemptId,
                    QuizName = quiz?.QuizName ?? "Unknown Quiz",
                    QuizDescription = quiz?.QuizDescription ?? "No description available",
                    Score = score,
                    TotalPossibleScore = totalPossibleScore,
                    FeedbackText = feedbackText
                };
                
                await DbContext.QuizFeedbacks.AddAsync(quizFeedback);
                await DbContext.SaveChangesAsync();
                Logger.LogInformation("Quiz feedback saved to database");
            }
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "Error generating or saving feedback: {Message}", ex.Message);
        }
    }

    private void RandomizeQuestions()
    {
        // Create a new random instance with a time-based seed
        Random random = new Random();
        
        // Create a shuffled copy of the questions list
        List<Question> shuffledQuestions = questions.OrderBy(_ => random.Next()).ToList();
        
        // Replace original list with shuffled list
        questions = shuffledQuestions;
    }
}